config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search
  get 'home/dashboard', to: 'home#dashboard', as: :dashboard


  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments
  resources :jobs
  resources :shifts
  resources :shift_jobs
  resources :pay_grades
  resources :pay_grade_rates
  resources :sessions

  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment
  patch 'shifts/:id/clock_in', to: 'shifts#clock_in', as: :clock_in
  patch 'shifts/:id/clock_out', to: 'shifts#clock_out', as: :clock_out

  # You can have the root of your site routed with 'root'
  root 'home#index'

  get 'employee/edit' => 'employee#edit', :as => :edit_current_employee
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'employees/search', to: 'employees#search', as: :employee_search
  get 'employees/:id/generate_payroll', to: 'employees#generate_payroll', as: :generate_payroll

  get 'stores/:id/payroll' => 'stores#store_payroll'
  post 'stores/:id/payroll' => 'stores#store_payroll', :as => :store_payroll

  get 'stores/:id/performance' => 'stores#performance', :as => :store_performance

end

app/models/employee.rb
class Employee < ApplicationRecord
  include AppHelpers::Validations
  include AppHelpers::Deletions
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods
  
  has_secure_password

  # Relationships
  has_many :assignments 
  has_many :stores, through: :assignments
  has_many :shifts, through: :assignments 
  has_many :pay_grades, through: :assignments
  has_many :pay_grade_rates, through: :pay_grades

  # Scopes
  scope :younger_than_18, -> { where('date_of_birth > ?', 18.years.ago.to_date) }
  scope :is_18_or_older,  -> { where('date_of_birth <= ?', 18.years.ago.to_date) }
  scope :regulars,        -> { where('role = ?', 'employee') }
  scope :managers,        -> { where('role = ?', 'manager') }
  scope :admins,          -> { where('role = ?', 'admin') }
  scope :alphabetical,    -> { order('last_name, first_name') }
  scope :search, ->(term) { where('first_name LIKE ? OR last_name LIKE ?', "#{term}%", "#{term}%") }

  # Validations
  validates_presence_of :first_name, :last_name, :ssn
  validates_date :date_of_birth, :on_or_before => lambda { 14.years.ago }, on_or_before_message: 'must be at least 14 years old'
  validates_format_of :phone, with: /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, message: 'should be 10 digits (area code needed) and delimited with dashes only'
  validates_format_of :ssn, with: /\A\d{3}[- ]?\d{2}[- ]?\d{4}\z/, message: 'should be 9 digits and delimited with dashes only'
  validates_uniqueness_of :ssn
  validates_inclusion_of :role, in: %w[admin manager employee], message: 'is not an option'
  # ... more validations for phase 4 & 5
  validates :username, presence: true, uniqueness: { case_sensitive: false}
  validates_presence_of :role, on: :create
  validates_presence_of :password, on: :create 
  validates_presence_of :password_confirmation, on: :create 
  validates_confirmation_of :password, on: :create, message: 'does not match'
  validates_length_of :password, minimum: 4, message: 'must be at least 4 characters long', allow_blank: true

  # Other methods
  def name
    "#{last_name}, #{first_name}"
  end
  
  def proper_name
    "#{first_name} #{last_name}"
  end

  def over_18?
    date_of_birth.to_date < 18.years.ago.to_date
  end
  
  def age
    (Time.now.to_s(:number).to_i - date_of_birth.to_time.to_s(:number).to_i)/10e9.to_i
  end

  def current_assignment
    curr_assignment = self.assignments.current    
    return nil if curr_assignment.empty?
    curr_assignment.first   # return as a single object, not an array
  end

  # Add in methods for phases 4 & 5 for authentication and payment handling
  include EmployeePayment
  include EmployeeAuthentication

  # Callbacks
  before_save -> { strip_nondigits_from(:phone) }
  before_save -> { strip_nondigits_from(:ssn) }

  # ... additional callbacks in phases 4 & 5
  include EmployeeDeletion
  before_destroy -> { handle_deletion_request() }
  after_rollback -> { handle_deletion_failure() }

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy, :generate_payroll]
  before_action :check_login
  authorize_resource

  def generate_payroll
    dates = DateRange.new(Date.today.to_date, 7.days.ago.to_date)
    payrollcalc = PayrollCalculator.new(dates)
    @payroll = payrollcalc.create_payroll_record_for(@employee)
  end

  def index
    # for phase 3 only
    if current_user.role?(:admin)
      @active_managers = Employee.managers.active.alphabetical.paginate(page: params[:page]).per_page(10)
      @active_employees = Employee.regulars.active.alphabetical.paginate(page: params[:page]).per_page(10)
      @inactive_employees = Employee.inactive.alphabetical.paginate(page: params[:page]).per_page(10)
    elsif current_user.role?(:manager)
      @active_managers = Employee.managers.active.alphabetical.select{|e| e.current_assignment.nil? ? false : e.current_assignment.store == current_user.current_assignment.store}
      @active_employees = Employee.regulars.active.alphabetical.select{|e| e.current_assignment.nil? ? false : e.current_assignment.store == current_user.current_assignment.store}
      @inactive_employees = Employee.regulars.inactive.alphabetical.select{|e| e.current_assignment.nil? ? false : e.current_assignment.store == current_user.current_assignment.store}
    end
  end

  def show
    dates = DateRange.new(Date.today.to_date, 7.days.ago.to_date)
    payrollcalc = PayrollCalculator.new(dates)
    @payroll = payrollcalc.create_payroll_record_for(@employee)
    retrieve_employee_assignments
    retrieve_employee_shifts
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to @employee, notice: "Successfully added #{@employee.proper_name} as an employee."
    else
      render action: 'new'
    end
  end

  def update
    if @employee.update_attributes(employee_params)
      redirect_to @employee, notice: "Updated #{@employee.proper_name}'s information."
    else
      render action: 'edit'
    end
  end


  def destroy
    if @employee.destroy
      redirect_to employees_url, notice: "Successfully removed #{@employee.proper_name} from the AMC system."
    else
      flash.now.alert = "Could not delete employee, was made inactive instead."
      render action: 'show'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :username, :ssn, :phone, :date_of_birth, :role, :active, :password, :password_confirmation)
  end

  def retrieve_employee_assignments
    @current_assignment = @employee.current_assignment
    @previous_assignments = @employee.assignments.to_a - [@current_assignment]
  end

  def retrieve_employee_shifts
    @shifts = @employee.shifts.all
    @previous_shifts = @employee.shifts.for_past_days(7)
    @upcoming_shifts = @employee.shifts.for_next_days(8)
    @pending_shifts_today = @employee.shifts.pending.for_date(Date.current)
    @started_shifts_today = @employee.shifts.started.for_date(Date.current)
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
  def number_to_ssn(num)
    "#{num[0..2]}-#{num[3..4]}-#{num[5..8]}"
  end
end

app/views/employees/_active_employees.html.erb
<%= render partial: 'employee_lists', locals: {employees: @active_employees, state: 'active'} %>

app/views/employees/_active_lists.html.erb
<%= render partial: 'employee_lists', locals: {employees: @active_managers, role: 'managers', state: 'active'} %>
<p>&nbsp;</p>
<%= render partial: 'employee_lists', locals: {employees: @active_employees, state: 'active', role: 'employees'} %>

app/views/employees/_assignment_history.html.erb
<% if @current_user.role?(:employee) %>
<div class="card">
    <div class="card-content">
        <span class="card-title">Payroll for Past Week</span>
        <table>
            <thead>
                <th>Hours Worked</th>
                <th>Pay Earned</th>
            </thead>
            <tr>
                <td><%=@payroll.hours%></td>
                <td><%=@payroll.pay_earned%></td>
            </tr>
        </table>
    </div>
    <div class="card-action">
        <a>><%= link_to "More Details", generate_payroll_url %></a>
    </div>
</div>
<br />
<% end %>
<% if current_user.role?(:employee)%>
<div class="card">
    <div class="card-content">
        <% if @pending_shifts_today.empty? %>
        <h5>No Shifts to Clock In</h5>
        <% else %>
        <h5>Shifts To Clock In</h5>

        <table class="striped highlight">
            <thead>
                <th>Start Time</th>
                <th>End Time</th>
                <th class="align_center">Clock In</th>
            </thead>
            <% @pending_shifts_today.each do |shift| %>
            <tr %>
                <td><%= shift.start_time.strftime("%l:%M %p") %></td>
                <td><%= shift.end_time.nil? ? "N/A" : shift.end_time.strftime("%l:%M %p") %></td>
                <td class="align_center">
                    <%= link_to(clock_in_path(shift), method: :patch) do %>
                    <i class="material-icons">timer</i>
                    <% end %>
                </td>
            </tr>
            <% end %>
        </table>
        <% end %>
    </div>
</div>
<div class="card">
    <div class="card-content">
        <% if @started_shifts_today.empty? %>
        <h5>No Shifts to Clock Out</h5>
        <% else %>
        <h5>Shifts To Clock Out</h5>

        <table class="striped highlight">
            <thead>
                <th>Start Time</th>
                <th>End Time</th>
                <th class="align_center">Clock Out</th>
            </thead>
            <% @started_shifts_today.each do |shift| %>
            <tr %>
                <td><%= shift.start_time.strftime("%l:%M %p") %></td>
                <td><%= shift.end_time.nil? ? "N/A" : shift.end_time.strftime("%l:%M %p") %></td>
                <td class="align_center">
                    <%= link_to(clock_out_path(shift), method: :patch) do %>
                    <i class="material-icons">timer_off</i>
                    <% end %>
                </td>
            </tr>
            <% end %>
        </table>
        <% end %>
        <br />
    </div>
</div>
<%end%>
<% unless @previous_assignments.nil? or @previous_assignments.empty?%>
<div class="card">
    <div class="card-content">
        <h5>Previous Assignments</h5>

        <table class="striped highlight">
            <thead>
                <th>Store</th>
                <th>Dates</th>
            </thead>
            <% @previous_assignments.each do |assignment| %>
            <tr %>
                <td><%= if can?(:view, assignment.store) then link_to assignment.store.name, store_path(assignment.store) else assignment.store.name end%></td>
                <td><%= assignment.start_date.strftime("%-m/%-d/%y") %> - <%= assignment.end_date.strftime("%-m/%-d/%y") %></td>
            </tr>
            <% end %>
        </table>
        <p class="supertiny"></p>
        <br />
    </div>
    <% if can? :create, Assignment %>
    <div class="card-action">
        <%= link_to "New Assignment", new_assignment_path(employee_id: @employee.id) %>
    </div>
    <% end %>
</div>
<% else %>
<% if can? :create, Assignment %>
<div class="card grey lighten-3">
    <div class="card-action">
        <%= link_to "New Assignment", new_assignment_path(employee_id: @employee.id) %>
    </div>
</div>
<% end %>
<% end %>

app/views/employees/_employee_data.html.erb
<div class="card">
  <div class="card-content">
    <h4><%= @employee.proper_name %></h4>
    <h5><%= @employee.role.capitalize %></h5>
    <h5><%= @employee.username %></h5>

    
    <br />

    <b>Current Assignment:&nbsp;&nbsp;</b><br>
      <% if @employee.current_assignment.nil? %>
        n/a<br /><br />
      <% else %>
        <%= link_to @employee.current_assignment.store.name, store_path(@employee.current_assignment.store) %><br />
        since <%= @employee.current_assignment.start_date.strftime("%b %-d, %Y") %><br /><br />

      <% end %>

    <b>Current Pay Grade:&nbsp;&nbsp;</b><br>
      <% if @employee.current_assignment.nil? or @employee.current_assignment.pay_grade.nil? %>
        n/a<br /><br />
      <% else %>
        <%= @employee.current_assignment.pay_grade.level %><br /><br />

      <% end %>
    
    <b>Current Pay Grade Rate:&nbsp;&nbsp;</b><br>
      <% if @employee.current_assignment.nil? or @employee.current_assignment.pay_grade.nil? or  @employee.current_assignment.pay_grade.current_pay_grade_rate.nil?%>
        n/a<br /><br />
      <% else %>
        <%= @employee.current_assignment.pay_grade.current_pay_grade_rate.rate %><br /><br />

      <% end %>

    <b>Phone:&nbsp;&nbsp;</b><br>
      <%= number_to_phone @employee.phone %><br /><br />

    <b>Social Security Number:&nbsp;&nbsp;</b><br>
      <%= number_to_ssn @employee.ssn %><br /><br />

    <b>Date of Birth:&nbsp;&nbsp;</b><br>
      <%= @employee.date_of_birth.to_datetime.strftime("%b %-d, %Y") %><br /><br />


    <b>Active with AMC?&nbsp;&nbsp;</b>
      <%= @employee.active ? "Yes" : "No" %>
      <br>
  </div>
</div>

app/views/employees/_employee_lists.html.erb
<div class="card">
  <div class="card-content">
    <h4><%= state.capitalize %> <%= role.capitalize %> at AMC</h4>

    <% if employees.nil? or employees.empty? %>
      <p>There are no <%= state.downcase %> <%= role.downcase %> at this time.</p>
    <% else %>
      <table class="striped highlight">
        <thead>
          <th>Name</th>
          <% unless state == 'inactive' %>
            <th>Current Assignment</th>
          <% end %>
          <th>Phone</th>
          <th class="align_center">Options</th>
        </thead>
        <% for employee in employees %>
          <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
            <td><%= if (can? :show, employee) then link_to employee.name, employee_path(employee) else employee.name end %></td>
            <% unless state == 'inactive' %>
              <td><%= employee.current_assignment.nil? ? 'n/a' : if (can? :show, employee.current_assignment.store) then link_to(employee.current_assignment.store.name, store_path(employee.current_assignment.store)) else employee.current_assignment.store.name end%></td>
            <% end %>
            <td><%= number_to_phone employee.phone %></td>
          <% if can? :edit, employee %>
            <td class="align_center">
              <%= link_to edit_employee_path(employee) do %>
                <i class="material-icons">edit</i>
              <% end %>
            </td>
          <% end %>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
      <%= if current_user.role?(:admin) then will_paginate employees, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" end %>
    <% end %>
  </div>
</div>

app/views/employees/_fields.html.erb
<%= f.input :first_name, label_html: { class: 'active' } %>
<%= f.input :last_name, label_html: { class: 'active' } %>
<%= f.input :username, label_html: { class: 'active' } %>
<%= f.input :ssn, label_html: { class: 'active' }%>
<%= f.input :password, label_html: { class: 'active' } %>
<%= f.input :password_confirmation, label_html: { class: 'active' } %>
<%= f.input :date_of_birth, label_html: { class: 'active' } %>
<%= f.input :phone, label_html: { class: 'active' } %>
<%= if current_user.role?(:admin) then f.input :role, collection: Employee::ROLES_LIST, include_blank: true end %>
<%= f.input :active %>

app/views/employees/_inactive_employees.html.erb
<%= render partial: 'employee_lists', locals: {employees: @inactive_employees, state: 'inactive', role: 'employees'} %>

app/views/employees/_upcoming_shifts.html.erb
<% unless @shifts.nil? or @shifts.empty?%>
  <div class="card">
    <div class="card-content">
    <% if @upcoming_shifts.empty? %>
      <h5>There are no upcoming shifts for <%= @employee.proper_name %></h5>
    <% else %>
      <h5>Upcoming and Current Shifts</h5>

      <table class="striped highlight">
        <thead>
          <th>Date</th>
          <th>Time</th>
          <th>Status</th>
          <% if can? :edit, Shift %>
            <th class="align_center">Options</th>
          <% end %>
        </thead>
        <% @upcoming_shifts.each do |shift| %>
          <tr %>
            <td><%= shift.date.strftime("%-m/%-d/%y") %></td>
            <td><%= shift.start_time.strftime("%l:%M %p") %> - <%= shift.end_time.strftime("%l:%M %p") %></td>
            <td><%= shift.status.capitalize %></td>
            <% if (can? :edit, shift) %>
              <td class="align_center">
                <%= link_to edit_shift_path(shift) do %>
                  <i class="material-icons">edit</i>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </table>
    <% end %>
    <br/>
    <% if @previous_shifts.empty? %>
      <h5>There are no past shifts for <%= @employee.proper_name %></h5>
    <% else %>
      <h5>Previous Shifts</h5>

      <table class="striped highlight">
        <thead>
          <th>Date</th>
          <th>Time</th>
          <th>Status</th>
          <% if can? :edit, Shift %>
            <th class="align_center">Edit</th>
          <% end %>
          <% if can? :show, Shift %>
            <th class="align_center">Details</th>
          <% end %>
        </thead>
        <% @previous_shifts.each do |shift| %>
          <tr %>
            <td><%= shift.date.strftime("%-m/%-d/%y") %></td>
            <td><%= shift.start_time.strftime("%l:%M %p") %> - <%= shift.end_time.strftime("%l:%M %p") %></td>
            <td><%= shift.status.capitalize %></td>
            <% if (can? :edit, shift) %>
              <td class="align_center">
                <%= link_to edit_shift_path(shift) do %>
                  <i class="material-icons">edit</i>
                <% end %>
              </td>
            <% end %>
            <% if (can? :show, shift) %>
              <td class="align_center">
                <%= link_to shift_path(shift) do %>
                  <i class="material-icons">reorder</i>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </table>
    <% end %>
      <p class="supertiny"></p>
      <br />
    </div>
    <% if can? :create, Shift %>
      <div class="card-action">
        <%= link_to "New Shift", new_shift_path(assignment_id: @employee.current_assignment.id) unless @employee.current_assignment.nil? %>
      </div>
    <% end %>
  </div>
<% else %>
  <% if can? :create, Shift %>
    <div class="card grey lighten-3">
      <div class="card-action">
        <%= link_to "New Shift", new_shift_path(assignment_id: @employee.current_assignment.id) unless @employee.current_assignment.nil? %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/employees/edit.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @employee, 
                                                        type_of_form: 'Employee',
                                                        fields: 'fields'} %>

app/views/employees/generate_payroll.html.erb
<% unless @payroll.nil? %>
<div class="card">
    <div class="card-content">
        <h5><%= @payroll.employee.proper_name %>'s past week pay roll information</h5>

        <table class="striped highlight">
            <thead>
                <th>Pay Grade</th>
                <th>Pay Rate</th>
                <th>Hours Worked</th>
                <th>Total Pay</th>
            </thead>
            <tr>
                <td><%= @payroll.pay_grade %></td>
                <td><%= @payroll.pay_rate %></td>
                <td><%= @payroll.hours %></td>
                <td><%= @payroll.pay_earned %></td>
            </tr>
        </table>
        <p class="supertiny"></p>
        <br />
    </div>
</div>
<% else %>
    <h4>No Pay Roll recorded for the past week</h4>
<% end %>

app/views/employees/index.html.erb
<%= render :partial => "partials/title_with_search", locals: { title: nil } %>
<%= render partial: 'partials/index_structure', locals: {model_name: 'employee', 
                                                         primary: 'active_lists', 
                                                         secondary: 'inactive_employees',
                                                         sidebar: nil} %>

app/views/employees/new.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @employee, 
                                                        type_of_form: 'New Employee',
                                                        fields: 'fields'} %>

app/views/employees/show.html.erb
<%= render partial: 'partials/show_structure', locals: {model_name: 'employee', 
                                                         object: @employee,
                                                         primary: 'employee_data', 
                                                         secondary: 'upcoming_shifts',
                                                         sidebar: 'assignment_history'} %>