config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search
  get 'home/dashboard', to: 'home#dashboard', as: :dashboard


  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments
  resources :jobs
  resources :shifts
  resources :shift_jobs
  resources :pay_grades
  resources :pay_grade_rates
  resources :sessions

  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment
  patch 'shifts/:id/clock_in', to: 'shifts#clock_in', as: :clock_in
  patch 'shifts/:id/clock_out', to: 'shifts#clock_out', as: :clock_out

  # You can have the root of your site routed with 'root'
  root 'home#index'

  get 'employee/edit' => 'employee#edit', :as => :edit_current_employee
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'employees/search', to: 'employees#search', as: :employee_search
  get 'employees/:id/generate_payroll', to: 'employees#generate_payroll', as: :generate_payroll

  get 'stores/:id/payroll' => 'stores#store_payroll'
  post 'stores/:id/payroll' => 'stores#store_payroll', :as => :store_payroll

  get 'stores/:id/performance' => 'stores#performance', :as => :store_performance

end

app/views/partials/_add_new_object.html.erb
<!-- Add a button for new instances of object -->
<% if can? :new, eval(model_name.camelize) %>
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-light btn") do %>
    <strong>Add a New <%= model_name.capitalize %></strong>
  <% end %>
<% end %>

app/views/partials/_display_base_errors.html.erb
<% unless object.errors.empty? %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box warning">
    <%= object.errors[:base].first %>
  </div>
<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
    <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer" class="center-align">
  
  <%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About A&M Creamery', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Privacy Policy', privacy_path %>
  <br />
  <div id="copy">
    Webmaster: <%= mail_to("kdonepud@cmu.edu", "Krishna Donepudi", encode: "javascript") %> 
    &nbsp;&nbsp;&copy 2020
  </div>

</div>

app/views/partials/_form_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields}", locals: { f: f } %>
          </div>
        </div>
      </div>
    </div>
      <div class="row">
        <div class="form-actions col s9">
          <%= f.button :submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_index_structure.html.erb
<div class="row">
  <div class="small-8 columns">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="small-4 columns">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

<!-- Add a button for new instances of object -->
<%= render :partial => 'partials/add_new_object', locals: {model_name: model_name} %>

app/views/partials/_nav.html.erb
<nav id="nav">
  <div class="container">
    <ul class="left hide-on-med-and-down">
      <% if (can? :edit, Store) %>
        <li><%= link_to 'Stores', stores_path %></li>
      <% end %>
       <% if (can? :index, Employee) %>
        <li><%= link_to 'Employees', employees_path %></li>
      <% end %>
      <% if (can? :index, Assignment) %>
        <li><%= link_to 'Assignments', assignments_path %></li>
      <% end %>
      <% if (can? :shifts, Shift) %>
        <li><%= link_to 'Shifts', shifts_path %></li>
      <% end %>
      <% if (can? :pay_grade, PayGrade) %>
        <li><%= link_to 'Pay Grades', pay_grades_path %></li>
      <% end %>
      <% if (can? :jobs, Job) %>
        <li><%= link_to 'Jobs', jobs_path %></li>
      <% end %>
    </ul>
    <ul class="right">
      <li><%= link_to 'My Account', employee_path(current_user) %></li>
      <li><%= link_to 'My Dashboard', dashboard_path %></li>
    </ul>
  </div>
</nav>

app/views/partials/_nav_guest.html.erb
<nav id="nav">
  <div class="container">
    <ul class="right">
      <li><%= link_to 'Login', login_path %></li>
    </ul>
  </div>
</nav>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
    <% if can?(:index, object) && controller.respond_to?(:index) %>
      <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn') do %>
        &nbsp;Display All <% model_name.pluralize.capitalize %>
      <% end %>
      &nbsp;&nbsp;
    <%end%>
  
  <% if can?(:edit, object) && controller.respond_to?(:update) %>
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  
  <% if can?(:destroy, object) && controller.respond_to?(:destroy)%>
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  <% end %>

</div>

app/views/partials/_show_structure.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s4">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>
<div class="row">
  <%= render :partial => 'partials/display_base_errors', locals: {object: object} %>
  <%= render :partial => 'partials/object_options', locals: {model_name: model_name, object: object} %>
</div>

app/views/partials/_title_with_search.html.erb
  <div class="row">
    <div class="col s7">
      <% unless title.nil? %>
        <div class = "center-align" ><h4><%= title %></h4></div>
      <% end %>
    </div>
    <div class="col s5">

          <%= form_with url: search_path, method: :get, class: "form-inline", id: "search" do %>
              <%= text_field_tag 'query', '', placeholder: "Search for Employees" %>
              <!-- submitting via js (press enter) so not using... -->
              <%# submit_tag('Find') %>
            
          <% end %>

    </div>
  </div>
  

app/views/partials/_topbar.html.erb
<div class="row valign-wrapper" id="topbar">
  <div class="col s1">
    <%# link_to(image_tag('logos/logo_v2_80x80.png'), home_path) %>
  </div>
  <div class="col s10">
    <h2><%= link_to 'A&M Creamery', home_path %></h2>
  </div>
  <div class="col s1">
    <% unless current_user.nil? %>
      <li><%= link_to 'Logout', logout_path %></li>
    <% end %>
  </div>
</div>