config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search
  get 'home/dashboard', to: 'home#dashboard', as: :dashboard


  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments
  resources :jobs
  resources :shifts
  resources :shift_jobs
  resources :pay_grades
  resources :pay_grade_rates
  resources :sessions

  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment
  patch 'shifts/:id/clock_in', to: 'shifts#clock_in', as: :clock_in
  patch 'shifts/:id/clock_out', to: 'shifts#clock_out', as: :clock_out

  # You can have the root of your site routed with 'root'
  root 'home#index'

  get 'employee/edit' => 'employee#edit', :as => :edit_current_employee
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'employees/search', to: 'employees#search', as: :employee_search
  get 'employees/:id/generate_payroll', to: 'employees#generate_payroll', as: :generate_payroll

  get 'stores/:id/payroll' => 'stores#store_payroll'
  post 'stores/:id/payroll' => 'stores#store_payroll', :as => :store_payroll

  get 'stores/:id/performance' => 'stores#performance', :as => :store_performance

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def privacy
  end

  def dashboard
    @stores = Store.active.alphabetical
    unless current_user.role?(:admin)
      @employees = Employee.active.regulars.alphabetical.select{|e| e.current_assignment.nil? ? false : e.current_assignment.store == current_user.current_assignment.store}
      @shifts = Shift.for_store(current_user.current_assignment.store).finished.select{ |s| !s.report_completed? }
    end
    dates = DateRange.new(Date.today.to_date, 7.days.ago.to_date)
    payrollcalc = PayrollCalculator.new(dates)
    @payroll = payrollcalc.create_payroll_record_for(current_user)
    @upcoming_shifts = current_user.shifts.for_next_days(8)
    @pending_shifts_today = current_user.shifts.pending.for_date(Date.current)
    @started_shifts_today = current_user.shifts.started.for_date(Date.current)
  end

  def search
    redirect_back(fallback_location: home_path) if params[:query].blank?
    @query = params[:query]
    if current_user.role?(:admin)
      @employees = Employee.search(@query)
    elsif current_user.role?(:manager)
      @employees = current_user.current_assignment.store.employees.search(@query)
    end
    @total_hits = @employees.size
  end
  
end

app/views/home/_admin_dashboard.html.erb
<div class = "row">
    <div class = "col s9">
        <% for store in @stores %>
            <div class="card">
                <div class="card-content">
                    <span class="card-title"><%= store.name %></span>
                    <b>Manager(s):&nbsp;&nbsp;</b><br>
                        <% for manager in store.assignments.current.select {|a| a.employee.role == "manager"} %>
                            <%= manager.employee.name %><br />
                        <% end %>
                    <b>Phone:&nbsp;&nbsp;</b>
                        <%= number_to_phone store.phone %><br />
                    <b>Employees Under 18:&nbsp;&nbsp;</b>
                        <%= store.assignments.current.select {|a| !a.employee.over_18? }.size %>
                </div>
                <div class="card-action">
                    <a><%=link_to "Payroll (2 Weeks)", store_payroll_path(store)%></a>
                    <a><%=link_to "Payroll (1 Month)", store_payroll_path(store, start_date: 1.month.ago)%></a>
                    <a><%=link_to "Performance Indicators", store_performance_path(store)%></a>
                </div>
            </div>
        <% end %>
    </div>
    <div class = "col s3">
        <div class = "right-align">
            <br>
            <div class="waves-effect waves-light btn">
                <i class="material-icons left">add</i>
                <%= link_to(new_assignment_path) do %>
                    <strong>New Assignment</strong>
                <% end %>
            </div>
            <br/>
            <br/>
            <div class="waves-effect waves-light btn">
                <i class="material-icons left">add</i>
                <%= link_to(new_store_path) do %>
                    <strong>New Store</strong>
                <% end %>
            </div>
            <br/>
            <br/>
            <div class="waves-effect waves-light btn">
                <i class="material-icons left">add</i>
                <%= link_to(new_employee_path) do %>
                    <strong>New Employee</strong>
                <% end %>
            </div>
            <br/>
            <br/>
            <div class="waves-effect waves-light btn">
                <i class="material-icons left">add</i>
                <%= link_to(new_pay_grade_path) do %>
                    <strong>New Pay Grade</strong>
                <% end %>
            </div>
            <br/>
            <br/>
            <div class="waves-effect waves-light btn">
                <i class="material-icons left">add</i>
                <%= link_to(new_job_path) do %>
                    <strong>New Job</strong>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/home/_employee_dashboard.html.erb
<div class = "row">
    <div class = "col s8">
        <div class="card">
            <div class="card-content">
            <% if @upcoming_shifts.nil? or @upcoming_shifts.empty? %>
                <h5>There are no upcoming shifts for <%= current_user.proper_name %></h5>
            <% else %>
                <h5>Upcoming Shifts</h5>
                <table class="striped highlight">
                <thead>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Status</th>
                </thead>
                <% @upcoming_shifts.each do |shift| %>
                    <tr %>
                    <td><%= shift.date.strftime("%-m/%-d/%y") %></td>
                    <td><%= shift.start_time.strftime("%l:%M %p") %> - <%= shift.end_time.strftime("%l:%M %p") %></td>
                    <td><%= shift.status.capitalize %></td>
                    </tr>
                <% end %>
                </table>
            <% end %>
                <p class="supertiny"></p>
                <br />
            </div>
        </div>
    </div>
    <div class = "col s4">
        <% if @current_user.role?(:employee) %>
<div class="card">
    <div class="card-content">
        <span class="card-title">Payroll for Past Week</span>
        <table>
            <thead>
                <th>Hours Worked</th>
                <th>Pay Earned</th>
            </thead>
            <tr>
                <td><%=@payroll.hours unless @payroll.nil?%></td>
                <td><%=@payroll.pay_earned unless @payroll.nil?%></td>
            </tr>
        </table>
    </div>
    <div class="card-action">
        <a>><%= link_to "More Details", generate_payroll_url(id: current_user.id) %></a>
    </div>
</div>
<br />
<% end %>
<% if current_user.role?(:employee)%>
<div class="card">
    <div class="card-content">
        <% if @pending_shifts_today.nil? or @pending_shifts_today.empty? %>
        <h5>No Shifts to Clock In</h5>
        <% else %>
        <h5>Shifts To Clock In</h5>

        <table class="striped highlight">
            <thead>
                <th>Start Time</th>
                <th>End Time</th>
                <th class="align_center">Clock In</th>
            </thead>
            <% @pending_shifts_today.each do |shift| %>
            <tr %>
                <td><%= shift.start_time.strftime("%l:%M %p") %></td>
                <td><%= shift.end_time.nil? ? "N/A" : shift.end_time.strftime("%l:%M %p") %></td>
                <td class="align_center">
                    <%= link_to(clock_in_path(shift), method: :patch) do %>
                    <i class="material-icons">timer</i>
                    <% end %>
                </td>
            </tr>
            <% end %>
        </table>
        <% end %>
    </div>
</div>
<div class="card">
    <div class="card-content">
        <% if @started_shifts_today.nil? or @started_shifts_today.empty? %>
            <h5>No Shifts to Clock Out</h5>
        <% else %>
            <h5>Shifts To Clock Out</h5>
        <table class="striped highlight">
            <thead>
                <th>Start Time</th>
                <th>End Time</th>
                <th class="align_center">Clock Out</th>
            </thead>
            <% @started_shifts_today.each do |shift| %>
            <tr %>
                <td><%= shift.start_time.strftime("%l:%M %p") %></td>
                <td><%= shift.end_time.nil? ? "N/A" : shift.end_time.strftime("%l:%M %p") %></td>
                <td class="align_center">
                    <%= link_to(clock_out_path(shift), method: :patch) do %>
                    <i class="material-icons">timer_off</i>
                    <% end %>
                </td>
            </tr>
            <% end %>
        </table>
        <% end %>
        <br />
    </div>
</div>
<%end%>

app/views/home/_manager_dashboard.html.erb
<div class = "row">
    <div class = "col s6">
        <% if @employees.nil? or @employees.empty? %>
            <h5>No one is employed at your store. Good luck!</h5>
        <% else %>
            <h4>Current Employees</h4>
            <% for employee in @employees %>
                <div class="card">
                    <div class="card-content">
                        <span class="card-title"><%= link_to employee.name, employee %></span>
                        <b>Phone:&nbsp;&nbsp;</b>
                            <%= number_to_phone employee.phone %><br />
                        <b>Hours Worked in Past Week:&nbsp;&nbsp;</b>
                            <%= employee.shifts.for_dates(DateRange.new(Date.today.to_date, 7.days.ago.to_date)).inject(0) { |hours, shift| hours + shift.duration} %><br />
                    </div>
                    <div class="card-action">
                        <a><%=link_to "Add Shift", new_shift_path(assignment_id: employee.current_assignment.id)%></a>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
    <div class = "col s6">
        <ul class = "right">
            <div class="waves-effect waves-light btn-large">
                <i class="large material-icons right">navigate_next</i>
                <%= link_to(current_user.current_assignment.store) do %>
                    <strong><%= current_user.current_assignment.store.name %></strong>
                <% end %>
            </div>
        </ul>
        <br/>
        <br/><br/>
        <div class = "card">
            <div class = "card-content">
            <% if @shifts.nil? or @shifts.empty? %>
                <h5> All shift reports completed! </h3>
            <% else %>
                <h4>Incomplete Shift Reports</h4>
                    <table>
                        <th>Employee</th>
                        <th>Date</th>
                        <th>Time</th>
                        <th class = "align_center">Options</th>
                        <% for shift in @shifts %>
                            <tr>
                                <td><%= shift.employee.first_name %></td>
                                <td><%= shift.date.strftime("%-m/%-d/%y")%></td>
                                <td><%= shift.start_time.strftime("%l:%M %p") %> - <%= shift.end_time.strftime("%l:%M %p") %></td>
                                <td class = "align_center">
                                    <%= link_to(shift) do %>
                                        <i class="material-icons">details</i>
                                    <% end %>
                                    <%= link_to(edit_shift_path(shift)) do %>
                                        <i class="material-icons">edit</i>
                                    <% end %>
                                    <%= link_to(new_shift_job_path(shift_id: shift.id)) do %>
                                        <i class="material-icons">add</i>
                                    <% end %>
                                <td>
                            </tr>
                        <% end %>
                    </table>
            <% end %>
            </div>
        </div>
    </div>
</div>

app/views/home/about.html.erb
<div class="row">
  <div class="small-7 columns">
    <h2><em>About the A &amp; M Creamery</em></h2>

    <p>
    	Started by H's sons we are a 100% test covered Creamery. We love chess
      players, bible quizzers, and Tom Brady. See the thing about this phase is
      it's hard and tedious and the midterm took only 1 hour haha.
    </p>
    <p>
      We have great ice cream and great interactions. Come over for a good time but not too long a time.
    </p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
  </div>
</div>

app/views/home/contact.html.erb
<div class="row">
	<div class="small-7 columns">
		<h2>Contact The Creamery</h2>
		<p class="supertiny">&nbsp;</p>
		<table cellpadding="3">
			<tr>
				<td>Webmaster:&nbsp;&nbsp;&nbsp;</td>
				<td>Krishna Donepudi</td>
			</tr>
			<tr>
				<td>Email:</td>
				<td>
				<%= mail_to("kdonepud@andrew.cmu.edu", "Krishna Donepudi", :encode => "javascript") %> 
				</td>
			</tr>
			<tr>
				<td>Phone:</td>
				<td>973-723-3246</td>
			</tr>
		</table>

		<p class="note"><br>Call the above number for job openings. 
			<br><br></p>
			
			<p>&nbsp;</p>
			<p>&nbsp;</p>
	</div>
</div>

app/views/home/dashboard.html.erb
<% if current_user.role?(:admin) %>
    <%= render :partial => "partials/title_with_search", locals: { title: "#{current_user.first_name}'s Dashboard "} %>
    <%= render partial: 'admin_dashboard' %>
<% elsif current_user.role?(:manager) %>
    <%= render :partial => "partials/title_with_search", locals: { title: "#{current_user.first_name}'s Dashboard "} %>
    <%= render partial: 'manager_dashboard' %>
<% else %>
    <%= render partial: 'employee_dashboard' %>
<% end %>

app/views/home/index.html.erb
<h5>A&M Creamery Home</h5>

<p>Check out our stores for the best ice cream:</p>

<iframe src="https://www.google.com/maps/d/u/0/embed?mid=1ES-Ycnziok5YFQHWTaA8e8iBtvRxdHhn" width="750" height="480"></iframe>
<br/>
<p>"He's not the Messiah - he's a very naughty boy."</p>
<p>"Look, I don't think it ought to be blasphemy, just saying 'Jehovah'."</p>
<p>"You're only making it worse for yourself!"</p>
<p>-Monty Python Quote for extra credit</p>

app/views/home/privacy.html.erb
<div class="row">    
  <div class="col s9">
    <div class="card">
      <div class="card-content">
        <span class="card-title"><em>The Creamery Privacy Policy</em></span>
        <p>Our privacy policy is simple and does not require a lawyer 
          to understand it.  
          We will pounce on the opportunity to sell every
          bit of information on you we have at our disposal in order 
          to boost our bottom line.  We will gladly sell your 
          address, phone, email, age, name of pet, name of
          favorite superhero, color of bunny slippers you wear at 
          home, and the like, to any willing buyer who will pay us the big bucks.  
          (BTW, we <em>know</em> you wear bunny slippers at home and   
          we know what color they are.  You really have no secrets 
          from us.)  If you have sensitive information that you don't want us to 
          share with the world, then keep it to yourself -- don't tell us.  
          <br><br>
          It's really that simple.
        </p>
        <p>&nbsp;</p>
      </div>
    </div>
  </div>
</div>

app/views/home/search.html.erb
<% if @employees.size == 1 %>
  <% controller.redirect_to employee_path(@employees.first) %>
<% end %>

<h5>Search result for term <em>'<%= @query %>'</em> resulted in <%= pluralize(@total_hits, 'hit') %></h5>
<p class="supertiny">&nbsp;</p>

<% if @employees.size > 1 %>
  <p><em><strong>employees matching term '<%= @query %>'</strong></em></p>
  <ul>
    <table class="striped highlight">
        <thead>
          <th>Name</th>
          <th>Current Assignment</th>
          <th>Phone</th>
          <th class="align_center">Options</th>
        </thead>
        <% for employee in @employees %>
          <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
            <td><%= if can?(:show, employee) then link_to employee.name, employee_path(employee) else employee.name end %></td>
            <td><%= if can?(:show, employee.current_assignment.store) then employee.current_assignment.nil? ? 'n/a' : link_to(employee.current_assignment.store.name, store_path(employee.current_assignment.store)) else employee.current_assignment.nil? ? 'n/a' : employee.current_assignment.store.name end%></td>
            <td><%= number_to_phone employee.phone %></td>

          <td class="align_center">
            <% if can?(:edit, employee) %>
              <%= link_to edit_employee_path(employee) do %>
                <i class="material-icons">edit</i>
              <% end %>
            <% end %>
          </td>
          </tr>
        <% end %>
    </table>
  </ul>
  <p class="smtext">&nbsp;</p>
<% end %>