config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search
  get 'home/dashboard', to: 'home#dashboard', as: :dashboard


  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments
  resources :jobs
  resources :shifts
  resources :shift_jobs
  resources :pay_grades
  resources :pay_grade_rates
  resources :sessions

  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment
  patch 'shifts/:id/clock_in', to: 'shifts#clock_in', as: :clock_in
  patch 'shifts/:id/clock_out', to: 'shifts#clock_out', as: :clock_out

  # You can have the root of your site routed with 'root'
  root 'home#index'

  get 'employee/edit' => 'employee#edit', :as => :edit_current_employee
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'employees/search', to: 'employees#search', as: :employee_search
  get 'employees/:id/generate_payroll', to: 'employees#generate_payroll', as: :generate_payroll

  get 'stores/:id/payroll' => 'stores#store_payroll'
  post 'stores/:id/payroll' => 'stores#store_payroll', :as => :store_payroll

  get 'stores/:id/performance' => 'stores#performance', :as => :store_performance

end

app/models/shift.rb
class Shift < ApplicationRecord
  include AppHelpers::Validations
  include AppHelpers::Deletions

  # Relationships
  belongs_to :assignment
  has_one :employee, through: :assignment
  has_one :store, through: :assignment
  has_many :shift_jobs #, dependent: :destroy
  has_many :jobs, through: :shift_jobs

  # Scopes
  scope :completed,     -> { joins(:shift_jobs).group(:shift_id) }
  scope :incomplete,    -> { joins("LEFT JOIN shift_jobs ON shifts.id = shift_jobs.shift_id").where('shift_jobs.job_id IS NULL') }
  # alternative ways of finding 'incomplete' scope:
  # scope :incomplete,  -> { where('id NOT IN (?)', Shift.completed.map(&:id)) }
  # also see the class method 'not_completed' further on down...
  scope :for_store,     ->(store) { joins(:assignment, :store).where("assignments.store_id = ?", store.id) }
  scope :for_employee,  ->(employee) { joins(:assignment, :employee).where("assignments.employee_id = ?", employee.id) }
  scope :past,          -> { where('date < ?', Date.current) }
  scope :upcoming,      -> { where('date >= ?', Date.current) }
  scope :pending,       -> { where('status = ?', 'pending') }
  scope :started,       -> { where('status = ?', 'started') }
  scope :finished,      -> { where('status = ?', 'finished') }
  scope :for_next_days, ->(x) { where('date BETWEEN ? AND ?', Date.current, x.days.from_now.to_date) }
  scope :for_past_days, ->(x) { where('date BETWEEN ? AND ?', x.days.ago.to_date, 1.day.ago.to_date) }
  scope :chronological, -> { order(:date, :start_time) }
  scope :by_store,      -> { joins(:assignment, :store).order(:name) }
  scope :by_employee,   -> { joins(:assignment, :employee).order(:last_name, :first_name) }
  # scope not in phase 4 requirements (b/c uses date range object)
  scope :for_dates,     ->(date_range) { where('date BETWEEN ? AND ?', date_range.start_date, date_range.end_date) }
  scope :for_date,     ->(date) { where('date = ?', date) }



  # Validations
  validates_date :date, on_or_after: lambda { :assignment_starts }, on_or_after_message: "must be on or after the start of the assignment"
  validates_time :start_time #, between: [Time.local(2000,1,1,11,0,0), Time.local(2000,1,1,23,0,0)]
  validates_time :end_time, after: :start_time, allow_blank: true
  validates_inclusion_of :status, in: %w[pending started finished], message: "is not an option"
  validate :assignment_must_be_current, on: :create
  validates_presence_of :assignment_id

  # Other methods
  def report_completed?
    self.shift_jobs.count > 0
  end
  
  # method uses the date_time_helpers gem; https://github.com/profh/time_date_helpers
  def duration
    (round_minutes(self.end_time) - round_minutes(self.start_time, direction: :down))/3600.0
  end
  
  # Callbacks
  # set default end_time (on create only)
  before_create :set_shift_end_time

  # allow shifts to only be deleted if status is 'pending'
  before_destroy do
    verify_shift_is_pending
    if errors.present?
      throw(:abort)
    end
  end

  # Misc Constants
  STATUS_LIST = [['Pending', 'pending'],['Started', 'started'],['Finished', 'finished']].freeze


  private
  def assignment_starts
    @assignment_starts = self.assignment.start_date.to_date
  end
  
  def assignment_must_be_current
    return true if self.assignment.nil?
    unless self.assignment.end_date.nil?
      errors.add(:assignment_id, "is not a current assignment at the creamery")
    end
  end
  
  def set_shift_end_time
    return true unless self.end_time.nil? 
    self.end_time = self.start_time + (3*60*60)
  end

  def verify_shift_is_pending
    unless self.status == 'pending'
      errors.add(:base, "This shift either has begun or has finished and cannot be deleted.")
    end
  end
  
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: [:show, :edit, :update, :destroy, :clock_in, :clock_out]
  before_action :check_login
	authorize_resource
	
	def index
    # get data on all shifts and paginate the output to 10 per page
    if current_user.role?(:admin)
      @past_shifts = Shift.past.chronological.paginate(page: params[:page]).per_page(10)
      @upcoming_shifts = Shift.upcoming.chronological.paginate(page: params[:ipage]).per_page(10)
    elsif current_user.role?(:manager)
      @past_shifts = Shift.past.chronological.for_store(current_user.current_assignment.store).paginate(page: params[:page]).per_page(10)
      @upcoming_shifts = Shift.upcoming.chronological.for_store(current_user.current_assignment.store).paginate(page: params[:ipage]).per_page(10)
    else
      @past_shifts = Shift.past.chronological.for_employee(current_user).paginate(page: params[:page]).per_page(10)
      @upcoming_shifts = Shift.upcoming.chronological.for_employee(current_user).paginate(page: params[:ipage]).per_page(10)
    end
  end

	def show
    @shift_jobs = @shift.shift_jobs
	end
	
	def new
    @shift = Shift.new
    @shift.assignment_id = params[:assignment_id] unless params[:assignment_id].nil?
    if current_user.role?(:manager)
      @assignments = current_user.current_assignment.store.assignments.current.chronological
      @assign_names = @assignments.map{|x| [x.employee.name, x.id]}
    else
      @assignments = Assignment.all.current.chronological
      @assign_names = @assignments.map{|x| [x.employee.name, x.id]}
    end
	end
	
  def edit
    if current_user.role?(:manager)
      @assignments = current_user.current_assignment.store.assignments.current.chronological
      @assign_names = @assignments.map{|x| [x.employee.name, x.id]}
    else
      @assignments = Assignment.all.current.chronological
      @assign_names = @assignments.map{|x| [x.employee.name, x.id]}
    end
  end

  def create
    @shift = Shift.new(shift_params)
    if @shift.save
      redirect_to @shift, notice: "Successfully added a #{@shift.status} shift for #{@shift.employee.name} to the system."
    else
      render action: 'new'
    end
	end

	def update
    if @shift.update_attributes(shift_params)
      redirect_to @shift, notice: "Updated shift information for shift #{@shift.id}."
    else
      render action: 'edit'
    end
  end

  def clock_in
    @new_time = TimeClock.new(@shift)
    @new_time.start_shift_at(Time.now)
    redirect_to @shift.employee
  end

  def clock_out
    @new_time = TimeClock.new(@shift)
    @new_time.end_shift_at(Time.now)
    redirect_to @shift.employee
  end
  
  def destroy
    if @shift.destroy
      redirect_to shifts_url, notice: "Successfully removed #{@shift.id} from the AMC system."
    else
      flash.now.alert = "Shift cannot be deleted if it is finished"
      redirect_to shifts_url
    end
  end

	
	private
  # Use callbacks to share common setup or constraints between actions.
  def set_shift
    @shift = Shift.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def shift_params
    params.require(:shift).permit(:assignment_id, :date, :start_time, :end_time, :notes, :status)
  end
	
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_current_upcoming_lists.html.erb
<%= render partial: 'shift_lists', locals: {shifts: @upcoming_shifts, state: 'Current and Upcoming'} %>

app/views/shifts/_fields.html.erb
<%= f.input :assignment_id, :collection => @assign_names, prompt: "Select employee" %>
<%= f.input :date, label_html: { class: 'active' } %>
<%= f.input :start_time, input_html: { class: 'timepicker' },label_html: { class: 'active' }, default: Time.now %>
<%= f.input :end_time, input_html: { class: 'timepicker' }, default: Time.now + 3.hours %>
<%= f.input :notes %>
<%= f.input :status, collection: Shift::STATUS_LIST, label_html: { class: 'active' } %>

app/views/shifts/_jobs.html.erb
<% unless @shift_jobs.nil? or @shift_jobs.empty?%>
  <div class="card">
    <div class="card-content">
      <h5>Jobs</h5>

      <table class="striped highlight">
        <% @shift_jobs.each do |shift_job| %>
          <tr %>
            <td><%= shift_job.job.name %></td>
            <% if can? :delete, shift_job %>
            <%= link_to(shift_job_path(shift_job), method: :delete, data: { confirm: 'Are you sure you wish to delete this job from this shift?' }) do %>
                <td><i class="material-icons">delete</i></td>
              <% end %>
            <% end%>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
    <% if can? :new, Shift %>
        <div class="card grey lighten-3">
          <div class="card-action">
            <%= link_to "Add a new job", new_shift_job_path(shift_id: @shift.id) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="card">
    <div class="card-content">
      <h5>No jobs associated with this shift</h5>
      <p class="supertiny"></p>
      <br />
      <% if can? :new, Shift %>
        <div class="card grey lighten-3">
          <div class="card-action">
            <%= link_to "Add a new job", new_shift_job_path(shift_id: @shift.id) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shifts/_past_lists.html.erb
<%= render partial: 'shift_lists', locals: {shifts: @past_shifts, state: 'past'} %>
<p>&nbsp;</p>

app/views/shifts/_shift_data.html.erb
<div class="card">
  <div class="card-content">
    <h4>Shift Number: <%= @shift.id %></h4>

    
    <br />
    <b>Shift Employee:&nbsp;&nbsp;</b><br>
      <%= @shift.employee.name %><br /><br />

    <b>Shift Store:&nbsp;&nbsp;</b><br>
      <%= @shift.store.name %><br /><br />

    <b>Date:&nbsp;&nbsp;</b><br>
      <%= @shift.date.strftime("%-m/%-d/%y") %><br /><br />

    <b>Start Time:&nbsp;&nbsp;</b><br>
      <%= @shift.start_time.strftime("%l:%M %p") %><br /><br />

    <b>End Time:&nbsp;&nbsp;</b><br>
      <%= @shift.end_time.nil? ? "n/a" : @shift.end_time.strftime("%l:%M %p") %><br /><br />

    <b>Status:&nbsp;&nbsp;</b><br>
      <%= @shift.status.capitalize %><br /><br />

    <b>Report Status:&nbsp;&nbsp;</b><br>
      <%= @shift.report_completed? ? "Yes" : "No" %><br /><br />

  </div>
</div>

app/views/shifts/_shift_lists.html.erb
<div class="card">
  <div class="card-content">
    <h4><%= if state == 'past' then state.capitalize else state end %> Shifts</h4>

    <% if shifts.nil? or shifts.empty? %>
      <p>There are no <%= state.downcase %> shifts at this time.</p>
    <% else %>
      <table class="striped highlight">
        <thead>
          <th>Name</th>
          <th>Store</th>
          <th>Data</th>
          <th>Start Time</th>
          <th>End Time</th>
          <th>Status</th>
          <th class="align_center">Options</th>
        </thead>
        <% for shift in shifts %>
          <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
            <td><%= if (can? :show, shift.employee) then link_to(shift.employee.name, employee_path(shift.employee)) else shift.employee.name end %></td>
            <td><%= if (can? :show, shift.store) then link_to(shift.store.name, store_path(shift.store)) else shift.store.name end%></td>
            <td><%= shift.date.strftime("%-m/%-d/%y") %></td>
            <td><%= shift.start_time.strftime("%l:%M %p") %></td>
            <td><%= shift.end_time.nil? ? "n/a" : shift.end_time.strftime("%l:%M %p") %></td>
            <td><%= shift.status.capitalize %></td>
          <% if can? :edit, shift %>
            <td class="align_center">
              <%= link_to edit_shift_path(shift) do %>
                <i class="material-icons">edit</i>
              <% end %>
              <%= link_to shift_path(shift) do %>
                <i class="material-icons">details</i>
              <% end %>
            </td>
          <% end %>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
      <%= will_paginate shifts, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
    <% end %>
  </div>
</div>

app/views/shifts/edit.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @shift, 
                                                        type_of_form: 'Shift',
                                                        fields: 'fields'} %>

app/views/shifts/index.html.erb
<%= render partial: 'partials/index_structure', locals: {model_name: 'shift', 
                                                         primary: 'current_upcoming_lists', 
                                                         secondary: 'past_lists',
                                                         sidebar: nil} %>

app/views/shifts/new.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @shift, 
                                                        type_of_form: 'Shift',
                                                        fields: 'fields'} %>

app/views/shifts/show.html.erb
<%= render partial: 'partials/show_structure', locals: {model_name: 'shift', 
                                                         object: @shift,
                                                         primary: 'shift_data', 
                                                         secondary: nil,
                                                         sidebar: 'jobs'} %>